# Generated by Django 3.2.5 on 2022-03-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=50, verbose_name='名字'),
        ),
    ]
